export const users = [
  {
    _id: '6645bff32e7ee60b28e504f0',
    index: 0,
    guid: 'ecfe87cd-5d5f-44cf-aa92-01706db4c144',
    isActive: false,
    balance: '$1,452.02',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'blue',
    name: 'Nunez Murphy',
    gender: 'male',
    company: 'PROXSOFT',
    email: 'nunezmurphy@proxsoft.com',
    phone: '+1 (990) 487-2625',
    address: '461 Columbus Place, Sardis, Puerto Rico, 3937',
    about:
      'Eu cillum officia esse magna exercitation dolor labore ad dolore cupidatat laborum. Consectetur irure pariatur enim velit cupidatat labore. Dolor ex commodo incididunt aliquip in aliqua laboris esse. Voluptate aliqua Lorem officia incididunt nulla anim sint irure velit. In esse incididunt deserunt in ea irure eu magna Lorem minim irure exercitation. Voluptate cillum et culpa id aliqua aute elit cupidatat occaecat. Pariatur voluptate veniam ipsum sunt nulla labore.\r\n',
    registered: '2018-03-03T07:31:17 -05:00',
    latitude: 87.391993,
    longitude: -42.153084,
    tags: [
      'mollit',
      'consectetur',
      'dolor',
      'pariatur',
      'do',
      'excepteur',
      'incididunt',
    ],
    friends: [
      {
        id: 0,
        name: 'Christina Mccormick',
      },
      {
        id: 1,
        name: 'Sonja Acosta',
      },
      {
        id: 2,
        name: 'Key Rodgers',
      },
    ],
    greeting: 'Hello, Nunez Murphy! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6645bff350947f815a75028e',
    index: 1,
    guid: 'e4999f3b-1164-4318-9540-64cb6d0c60f8',
    isActive: false,
    balance: '$1,714.50',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'green',
    name: 'Johnston Hoffman',
    gender: 'male',
    company: 'OPTICOM',
    email: 'johnstonhoffman@opticom.com',
    phone: '+1 (820) 591-2711',
    address: '153 Crystal Street, Chemung, Alabama, 5741',
    about:
      'Excepteur aliquip id nisi deserunt excepteur ad cillum est aliquip irure ex. Fugiat ut excepteur eiusmod qui in Lorem tempor qui laborum incididunt sint labore amet velit. Magna id aute eu officia in laboris labore commodo. Consectetur eu ut enim in fugiat quis amet.\r\n',
    registered: '2021-06-24T05:16:21 -05:00',
    latitude: -13.597068,
    longitude: -66.149304,
    tags: ['consequat', 'occaecat', 'elit', 'esse', 'aute', 'ex', 'labore'],
    friends: [
      {
        id: 0,
        name: 'Lynette Goodwin',
      },
      {
        id: 1,
        name: 'Hansen Vang',
      },
      {
        id: 2,
        name: 'Leticia Heath',
      },
    ],
    greeting: 'Hello, Johnston Hoffman! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6645bff37e61b830c903c67c',
    index: 2,
    guid: 'b3d20079-9294-4692-b3dd-df6b1d9f9d4e',
    isActive: false,
    balance: '$3,002.12',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'blue',
    name: 'Ayers Maxwell',
    gender: 'male',
    company: 'DIGIFAD',
    email: 'ayersmaxwell@digifad.com',
    phone: '+1 (931) 522-2062',
    address: '321 Desmond Court, Ticonderoga, Delaware, 6200',
    about:
      'Et id exercitation dolor adipisicing sint fugiat magna exercitation cupidatat ut anim. Dolor ea qui exercitation duis occaecat ullamco dolor cupidatat nulla minim. Officia eu amet consequat officia sit id eiusmod dolore deserunt ea proident. Tempor pariatur laboris officia laboris pariatur est occaecat adipisicing ullamco minim id duis velit. Ullamco magna pariatur minim pariatur elit.\r\n',
    registered: '2023-11-05T02:41:05 -05:00',
    latitude: -76.551605,
    longitude: 156.712935,
    tags: ['irure', 'ad', 'ad', 'in', 'cupidatat', 'exercitation', 'id'],
    friends: [
      {
        id: 0,
        name: 'Hayes Shepard',
      },
      {
        id: 1,
        name: 'Snow Richards',
      },
      {
        id: 2,
        name: 'Rice Gill',
      },
    ],
    greeting: 'Hello, Ayers Maxwell! You have 7 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6645bff39ecbb46bf662fbc4',
    index: 3,
    guid: 'e4b5010d-093e-4229-bec9-b0a9c91faf6e',
    isActive: false,
    balance: '$3,707.98',
    picture: 'http://placehold.it/32x32',
    age: 29,
    eyeColor: 'brown',
    name: 'Richards Conner',
    gender: 'male',
    company: 'GEEKOSIS',
    email: 'richardsconner@geekosis.com',
    phone: '+1 (827) 438-3066',
    address: '934 Lenox Road, Retsof, Massachusetts, 9925',
    about:
      'Dolore proident fugiat irure laborum elit officia duis minim eu consequat laboris eiusmod eiusmod aliqua. Quis ad elit ea eu magna adipisicing sunt. Anim commodo do exercitation pariatur.\r\n',
    registered: '2023-04-26T02:13:23 -05:00',
    latitude: -58.929033,
    longitude: 48.37325,
    tags: ['deserunt', 'veniam', 'aliquip', 'esse', 'anim', 'ea', 'labore'],
    friends: [
      {
        id: 0,
        name: 'Cruz Vinson',
      },
      {
        id: 1,
        name: 'Lucile Fry',
      },
      {
        id: 2,
        name: 'Gray Cantrell',
      },
    ],
    greeting: 'Hello, Richards Conner! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6645bff3b0370230d35341be',
    index: 4,
    guid: '41e08c70-fadf-4522-9e32-b9dc7751b26d',
    isActive: true,
    balance: '$3,636.83',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Maggie Zimmerman',
    gender: 'female',
    company: 'QUARX',
    email: 'maggiezimmerman@quarx.com',
    phone: '+1 (813) 420-2465',
    address: '328 Rost Place, Juarez, Nevada, 3426',
    about:
      'Cupidatat aliqua ea non sit id exercitation. Adipisicing voluptate consequat sint ad magna ipsum ad laborum nisi. Dolor tempor sit deserunt sit. Id dolor irure qui velit cupidatat incididunt veniam minim adipisicing. Ut pariatur minim nulla ut cupidatat consectetur ad commodo ut. Commodo ullamco ea elit ad mollit enim cupidatat velit aliqua et minim qui commodo. Do pariatur sint incididunt labore cupidatat non cillum.\r\n',
    registered: '2018-06-15T12:53:17 -05:00',
    latitude: 24.245902,
    longitude: 159.07715,
    tags: [
      'cillum',
      'nulla',
      'laborum',
      'deserunt',
      'amet',
      'commodo',
      'dolor',
    ],
    friends: [
      {
        id: 0,
        name: 'Morales Landry',
      },
      {
        id: 1,
        name: 'Opal Avery',
      },
      {
        id: 2,
        name: 'Lora Kaufman',
      },
    ],
    greeting: 'Hello, Maggie Zimmerman! You have 7 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6645bff3ff405d7981d3c9e2',
    index: 5,
    guid: '2a4f9eb9-8688-42f1-be75-f9f07234e1b4',
    isActive: true,
    balance: '$3,627.02',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: 'Finch Richmond',
    gender: 'male',
    company: 'CINESANCT',
    email: 'finchrichmond@cinesanct.com',
    phone: '+1 (874) 580-3952',
    address: '347 Elliott Place, Fontanelle, American Samoa, 7046',
    about:
      'Quis nisi laborum est anim velit. Tempor anim amet aliquip aliqua sint commodo excepteur consequat voluptate. Sit cillum excepteur amet ut labore nostrud. Incididunt est eiusmod fugiat anim fugiat esse exercitation excepteur magna. Proident aliquip non aute et aliqua nulla eiusmod.\r\n',
    registered: '2023-08-03T06:14:01 -05:00',
    latitude: -45.940201,
    longitude: 146.463471,
    tags: [
      'occaecat',
      'incididunt',
      'exercitation',
      'sit',
      'nulla',
      'non',
      'eiusmod',
    ],
    friends: [
      {
        id: 0,
        name: 'William Pruitt',
      },
      {
        id: 1,
        name: 'Perkins Huffman',
      },
      {
        id: 2,
        name: 'Leann Maldonado',
      },
    ],
    greeting: 'Hello, Finch Richmond! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6645bff3060d0b0573565f97',
    index: 6,
    guid: '64881222-5b0e-4196-8fce-644aed4f1103',
    isActive: false,
    balance: '$1,194.74',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: 'Lauri Mcdaniel',
    gender: 'female',
    company: 'FUELWORKS',
    email: 'laurimcdaniel@fuelworks.com',
    phone: '+1 (914) 495-2117',
    address: '320 Balfour Place, Alfarata, New York, 4401',
    about:
      'Eiusmod ex nisi nulla irure sunt est et id sunt. Et dolor esse dolore et tempor eu excepteur sint veniam voluptate tempor aliquip consequat. Nostrud pariatur laborum commodo ad esse anim adipisicing incididunt.\r\n',
    registered: '2015-09-18T01:00:13 -05:00',
    latitude: -41.335161,
    longitude: 57.703404,
    tags: ['excepteur', 'pariatur', 'ex', 'et', 'incididunt', 'et', 'amet'],
    friends: [
      {
        id: 0,
        name: 'Mcdaniel Lucas',
      },
      {
        id: 1,
        name: 'Keri Mack',
      },
      {
        id: 2,
        name: 'Barker Bryan',
      },
    ],
    greeting: 'Hello, Lauri Mcdaniel! You have 9 unread messages.',
    favoriteFruit: 'apple',
  },
];
